# Generated by Django 5.1.3 on 2024-12-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
