# Generated by Django 5.1.3 on 2024-12-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_feedback_customer_name_remove_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
